import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";

const plusJakartaSans = Plus_Jakarta_Sans();

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const glamourAbsolute = localFont({
  src: "../fonts/glamour_absolute_regular.ttf",
  variable: "--font-glamour-absolute",
  display: "swap",
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.className} ${glamourAbsolute.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
